name: Update README with Latest Posts

on:
  # Trigger after posts workflow completes successfully
  workflow_run:
    workflows: ["Substack Posts Scraper"]
    types:
      - completed

  # Allow manual trigger
  workflow_dispatch:

  # Also trigger on push to posts folder (for testing)
  push:
    branches:
      - main
    paths:
      - 'substack-scraper/posts/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    # Only run if the posts workflow succeeded (or if manually triggered)
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      github.event.workflow_run.conclusion == 'success'

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Need to fetch the latest changes from posts workflow
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update README with latest posts
        run: |
          cd substack-scraper
          python update_readme.py

      - name: Check for changes
        id: git-check
        run: |
          if [[ -n $(git status --porcelain README.md) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "README was updated!"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes to README"
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest blog posts

          🤖 Generated with [Claude Code](https://claude.com/claude-code)
          via [Happy](https://happy.engineering)

          Co-Authored-By: Claude <noreply@anthropic.com>
          Co-Authored-By: Happy <yesreply@happy.engineering>"
          git push
